spring.application.name=backend

# Informações sobre o banco de dados [Entrega 3]
spring.datasource.url=jdbc:postgresql://localhost:5432/saep_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA - Automação da criçãpo das tabelas do banco de dados
spring.jpa.hibernate.ddl-auto=update

# Mostra o SQL no terminal
spring.jpa.show-sql=true

# Utilização de termos especificos do PostgreSQL para otimizar consultas
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect